### ISSUE TITLE
No updates

### ISSUE THREAD

**Issue by elronat** [shepherdjerred/better-skill-capped#159]
Hi,
there´re new videos on skill-capped.com but they´re not shown on the site yet. Is there a way to update it manually?

Greetings

**Comment by shepherdjerred** [comment]
Hello! Sorry for the late reply; it turns out that I wasn't watching this repository for issues. It looks like the videos are up-to-date as of today. I think back in March there was an issue with the AWS Lambda function timing out, but that has been fixed. Let me know if there are any other videos missing.
